apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-user
  name: udagram-api-user
spec:
  selector:
    matchLabels:
      service: udagram-api-user
  replicas: 2
  template:
    metadata:
      labels:
        service: udagram-api-user
    spec:
      containers:
      - image: omarzztelcocloud/udagram-api-user:v4
        name: udagram-api-user
        envFrom:
          - configMapRef:
              name: envconfigmap
          - secretRef:
              name: envsecret
        imagePullPolicy: Always     
        ports:
        - containerPort: 8080


